//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiket_reservation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiket_54414156Entities : DbContext
    {
        public tiket_54414156Entities()
            : base("name=tiket_54414156Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<detil_pesan_tiket> detil_pesan_tiket { get; set; }
        public DbSet<pajak_bandara> pajak_bandara { get; set; }
        public DbSet<Pembeli> Pembeli { get; set; }
        public DbSet<Pembeli_validasi> Pembeli_validasi { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tgl_pesan> tgl_pesan { get; set; }
    }
}
